Allow building Sphinx docs
open-mpi/ompi-scripts pull request #55
Opened 2022-02-13 15:18 UTC by jsquyres

If docs/requirements.txt exists in the source tree, that means that we
have Sphinx documentation, not Pandoc documentation.  Create a Python
virtual environment before running configure and install the Right
things for Sphinx to build the man pages.  This also means that there
will be no Pandoc-generated man pages, so don't bother trying to
convert them to HTML.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

2022-02-13 15:20 UTC, jsquyres commented
@bwbarrett I'm not entirely sure that this is correct; I could use your guidance here.  The intent for this PR is to support https://github.com/open-mpi/ompi/pull/8329 by allowing building the Sphinx docs if they are present (and skip doing some Pandoc things).  Once https://github.com/open-mpi/ompi/pull/8329 merges, we can further simplify a few things here in ompi-scripts by fully removing all Pandoc things.

2022-02-14 16:50 UTC, bwbarrett requested changes

2022-02-14 16:50 UTC, bwbarrett commented on jenkins/open-mpi-build-script.sh
> +if test -f docs/requirements.txt; then
This script runs every time a job starts.  So you're building a new environment 1) in the OMPI tree and 2) every build.  That's pretty wasteful.  I can't remember if we're making Spinx required (as in, must have, or can't build OMPI) or optional (like pandoc).

If it's optional like pandoc, I think following the pandoc "if the executable isn't already available, add the --disable flag".

If it's not optional, then we should do caching, similar to the autogen tools in the dist script.

2022-02-15 23:35 UTC, bwbarrett commented on jenkins/open-mpi-build-script.sh
> +if test -f docs/requirements.txt; then
Jeff and I talked offline about this and decided that the right answer was just to install Sphinx on the build AMIs.  I did this today, so we shouldn't need this part of the commit (but may need other parts, below).

2022-02-15 23:35 UTC, bwbarrett commented on jenkins/open-mpi.dist.create-tarball.groovy
> +if test ! -f docs/requirements.txt; then
Maybe a comment about why we do this?  Just to confirm, we're going to use read the docs for the official docs, right?

2022-02-15 23:35 UTC, bwbarrett commented on jenkins/open-mpi.dist.create-tarball.groovy
> +if test -f docs/requirements.txt; then
Similar to the top bit, I think we can drop this now.

2022-03-08 14:56 UTC, bwbarrett requested changes

2022-03-08 14:56 UTC, bwbarrett commented on jenkins/open-mpi-build-script.sh
> +# Keep pandoc for now; when Sphinx is brought to the v5.0.x branch, we
We run CI tests on branches prior to 5.0.x, so we can't remove this block for some time.  That said, it needs to change.  I think the logic becomes:

1) if no --disable-man-pages option to configure, do nothing. (this is a pre-pandoc build)
2) if docs/requirements.txt exists, do nothing (this is a 5.0.x or later build, so configure will autoselct forward whether or not Sphinx is found).
3) if pandoc is found, do nothing (this is a pandoc-era build, and we have pandoc)
4) else, add --disable-man-pages to configure (this is a pandoc-era build, and we don't have pandoc, so we need to add a configure argument to let the build succeed).

2022-08-17 15:10 UTC, closed without merging